import {articles} from './articles.js?v=20260921-adventure';
import {strings} from './strings.js?v=20260921-adventure';
import {guides} from './guides.js';
import {ratesAt} from './rates.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'ja',D,page=1;
const tr=k=>strings[k]?.[lang==='en'?1:0]??articles[k]?.title[lang==='en'?1:0]??k,L=v=>v&&typeof v==='object'&&!Array.isArray(v)?v[lang]??v.ja??'':v??'',T=v=>Array.isArray(v)?v[lang==='en'?1:0]:L(v);
const nav=['home','guide','characters','skills','equipment','cards','quests','dungeons','events','summons','story','camp','combat','growth','faq','about'];
const icons=['⌂','◇','♧','✧','⚒','▧','▤','♜','✦','☆','▱','♨','◎','△','?','↗'];
const href=(type,id)=>'#'+type+(id?'/'+encodeURIComponent(id):''),link=(type,id,text)=>`<a href="${href(type,id)}">${esc(text)}</a>`,tag=s=>`<span class="badge">${esc(s)}</span>`,heading=(s,p='')=>`<h1>${esc(s)}</h1>${p?`<p class="muted">${esc(p)}</p>`:''}`,section=(s,body)=>`<section class="panel"><h2>${esc(s)}</h2>${body}</section>`,table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const get=(group,id)=>D[group].find(x=>x.id===id);
const picture=(src,alt,cls='card-image')=>src?`<img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" loading="lazy">`:'',element=id=>({fire:['火','Fire'],water:['水','Water'],wind:['風','Wind'],light:['光','Light'],dark:['闇','Dark'],none:['無属性','None']})[id]?.[lang==='en'?1:0]||'—';
function portrait(c){if(c.portrait!=null)return `<span class="portrait" role="img" aria-label="${esc(L(c.name))}" style="background-image:url('${D.portraitAtlas}');background-position:-${c.portrait%12*96}px -${Math.floor(c.portrait/12)*96}px"></span>`;return `<span class="new-portrait ${esc(c.id)}" role="img" aria-label="${esc(L(c.name))}" style="background-image:url('${esc(c.art)}')"></span>`;}
function charCard(c){return `<a class="card character-card" href="${href('character',c.id)}"><div class="portrait-wrap">${portrait(c)}</div><div class="card-body"><span class="stars">${'★'.repeat(c.rarity)}</span><h3>${esc(L(c.name))}</h3><p>${esc(L(c.role))} · ${esc(element(c.element))}</p>${tag(tr(c.acquisition==='story'?'storyOnly':c.acquisition))}</div></a>`;}
function itemCard(c){return `<a class="card" href="${href('item',c.id)}">${picture(c.art,L(c.name),'card-square')}<div class="card-body">${tag('★'+(c.tier||'—'))}<h3>${esc(L(c.name))}</h3><p>${esc(L(c.description))}</p></div></a>`;}
function eventCard(e){return `<a class="card" href="${href('event',e.id)}">${picture(e.art,L(e.name))}<div class="card-body"><span class="eyebrow">${e.month} / ${tr(e.half===1?'firstHalf':'secondHalf')} · JST</span><h3>${esc(L(e.name))}</h3><p>${esc(L(e.boss))}</p></div></a>`;}
function routeArt(kind){if(['event-guide','coop-guide','events'].includes(kind)){const d=new Date(Date.now()+9*3600000);return D.events.find(e=>e.month===d.getUTCMonth()+1&&e.half===(d.getUTCDate()<16?1:2)).art;}return ({'story-guide':'assets/forest-camp-chapter2.png',story:'assets/forest-camp-chapter2.png','dungeon-guide':D.hero,dungeons:D.hero,'quest-guide':'assets/quest-guild-board-v1.png',quests:'assets/quest-guild-board-v1.png','camp-guide':'assets/forest-camp-chapter2.png',camp:'assets/forest-camp-chapter2.png','background-guide':D.hero,'growth-guide':'assets/training-companions-v1.png',growth:'assets/training-companions-v1.png',recommendations:'assets/training-companions-v1.png','cards-guide':D.equipment.find(c=>c.id==='ability_amberorchard_5').art,cards:D.equipment.find(c=>c.id==='ability_amberorchard_5').art})[kind]||D.hero;}
function pageHero(kind,title,description=''){if(!description)description=T(({dungeons:['灯りを携えて、まだ見ぬお宝へ。ランクと報酬から、次の探索先を選びましょう。','Carry a light toward undiscovered treasures. Choose your next expedition by rank and rewards.'],quests:['掲示板に届いた、小さな物語。依頼を解決して、旅を変える一枚を。','Small stories await on the guild board. Fulfil a request and discover a card for your next journey.'],events:['季節ごとに訪れる強敵と、新しい仲間。気になる舞台から、次の冒険を探しましょう。','Seasonal foes and new companions await. Find the setting for your next adventure.'],characters:['得意な役割も、歩んできた物語も、一人ひとり違う。次に迎えたい仲間を見つけよう。','Every companion brings a different role and story. Find someone new to travel with.'],cards:['一枚を選ぶ楽しさが、編成を変える。相性のよい効果を見つけて、作戦を広げよう。','One card can reshape a party. Find effects that work together and build a new strategy.'],equipment:['剣を研ぎ、防具を整え、次の強敵へ。仲間に合う装備を探しましょう。','Prepare your weapons and armor for the next challenge. Find gear that suits your companions.'],camp:['焚き火を囲む時間も、冒険の一部。出発前の道具選びに、次の作戦を込めて。','Time around the fire is part of the adventure. Choose your supplies for the road ahead.']})[kind]||['旅の途中で気になったことを、ここでひとつずつ。次の冒険に役立つヒントをまとめました。','Find answers and ideas for the road ahead. Explore these notes before your next adventure.']);return `<section class="page-hero"><img src="${esc(routeArt(kind))}" alt="" loading="lazy"><div><span class="eyebrow">CAMPFIRE TACTICS · FIELD NOTES</span><h1>${esc(title)}</h1>${description?`<p>${esc(description)}</p>`:''}</div></section>`;}
function articlePage(id){const a=articles[id];return pageHero(id,T(a.title),T(a.intro))+`<div class="article-index">${a.sections.map((x,i)=>`<a href="#${id}" data-section="article-${i}">${String(i+1).padStart(2,'0')} · ${esc(T(x[0]))}</a>`).join('')}</div><div class="prose">${a.sections.map((x,i)=>`<section class="panel" id="article-${i}"><span class="eyebrow">FIELD GUIDE ${String(i+1).padStart(2,'0')}</span><h2>${esc(T(x[0]))}</h2><p>${esc(T(x[1]))}</p></section>`).join('')}</div>`+section(T(['次に読みたい','Continue exploring']),`<div class="linklist">${a.links.map(k=>`<a href="#${k}">${esc(tr(k))}</a>`).join('')}</div>`);}
function adventureHub(){return `<div class="section-title"><h2>${T(['今日は、どんな冒険にしよう。','Where will today’s adventure lead?'])}</h2></div><div class="feature-grid">${[
['story-guide','01',['物語を進める','Follow the story'],['第二章の難所まで、仲間と歩む道しるべ。','Find your way through the chapters and their challenges.']],
['dungeon-guide','02',['お宝を探しに','Hunt for treasure'],['装備を更新し、番人を越え、探索を仲間に任せる。','Find gear, beat the guardians, and unlock background expeditions.']],
['quest-guide','03',['掲示板をのぞく','Visit the notice board'],['小さな物語と、45枚の特化カードを集めよう。','Discover small stories and collect 45 specialist cards.']],
['coop-guide','04',['仲間と共闘する','Join a co-op expedition'],['冒険者カードでつながる仲間。戦利品はダイスで。','Meet companions through adventurer cards; draft your loot with dice.']],
['recommendations','05',['次に育てるのは？','Who will you train next?'],['目的別おすすめと、編成に迎えたい理由。','Purpose-based recommendations, with reasons for every choice.']],
['schedule','06',['次の出会いを待つ','Plan your next summon'],['週間ピックアップ、期間限定、3つのフェス。','Weekly pickups, seasonal companions and three festivals.']]
].map(([id,n,title,desc])=>`<a class="feature-tile" href="#${id}">${picture(routeArt(id),T(title),'feature-art')}<span class="eyebrow">ADVENTURE ${n}</span><h3>${T(title)} →</h3><p>${T(desc)}</p></a>`).join('')}</div><div class="linklist feature-secondary">${['cards-guide','camp-guide','friends-guide','growth-guide'].map(k=>`<a href="#${k}">${tr(k)}</a>`).join('')}</div>`;}
function schedulePage(){const now=Date.now(),jst=new Date(now+9*3600000),day0=Date.UTC(jst.getUTCFullYear(),jst.getUTCMonth(),jst.getUTCDate())-9*3600000;return pageHero('schedule',tr('schedule'),T(['日付は日本時間。次の28日間の出会いを、旅の予定に。','All dates use Japan time. Plan your encounters for the next 28 days.']))+`<div class="split">${['rukiwa','milena','nonoa'].map((id,i)=>featuredCompanion(get('characters',id),T([['毎週日曜日','毎月11日・22日','毎月7日・17日・27日'][i],['Every Sunday','11th & 22nd each month','7th, 17th & 27th each month'][i]]))).join('')}</div>`+section(T(['召喚の選び方','Choose a banner']),`<p>${T(['常設・週間ピックアップ・期間限定・開催日のフェスがあります。週間は木曜15:00、期間限定は毎月1日・16日の0:00に切り替わります。★5は合計5%、ピックアップ★5は2.5%です。提供割合は召喚ページで全員分を確認できます。','Choose permanent, weekly, seasonal, or active festival banners. Weekly pickups change Thursday at 15:00; seasonal banners change on the 1st and 16th at 00:00. The total ★5 rate is 5%; a featured ★5 has a 2.5% rate. See the summon page for individual rates.'])}</p><a href="#summons">${tr('summons')} →</a>`)+`<div class="calendar-grid">${Array.from({length:28},(_,i)=>{const t=day0+i*86400000,d=new Date(t+9*3600000),e=D.events.find(e=>e.month===d.getUTCMonth()+1&&e.half===(d.getUTCDate()<16?1:2)),f=['sunday','doubles','seven'].filter(k=>ratesAt(D,k,t).available),w=ratesAt(D,'weekly',t).rows.find(r=>r.pickup&&r.rarity===5);return `<section class="calendar-day ${f.length?'festival-day':''}"><strong>${d.getUTCMonth()+1}/${d.getUTCDate()}${i===0?' · '+T(['今日','Today']):''}</strong>${f.map(k=>`<p>${tag(tr(k))}${link('character',ratesAt(D,k,t).rows.find(r=>r.pickup).id,L(get('characters',ratesAt(D,k,t).rows.find(r=>r.pickup).id).name))}</p>`).join('')}<small>${tr('weekly')} · ${esc(L(get('characters',w.id).name))}</small><small>${tr('limited')} · ${esc(L(get('characters',e.characterId).name))}</small></section>`;}).join('')}</div>`;}
function recommendationsPage(){const groups=[
[['最初の5人を支える育成候補','Early-party priorities'],[
['hina',['回復役を先に確保したいとき。Lv1の回復とLv15の祈りを軸に、前衛の後ろから支えます。','An early healing option, with healing at Lv1 and Prayer at Lv15. Keep her behind the frontline.']],
['brann',['前衛を安定させたいとき。Lv1から挑発が使えるタンク。回復役や魔法役への接近を抑える役割を持たせましょう。','A tank with taunt from Lv1. Use him to reduce pressure on your healer and mages.']],
['fina',['魔法攻撃を編成へ足したいとき。Lv15のメテオを目標に育成し、複数の敵へ届く場面を狙います。','Add magic damage and work toward Meteor at Lv15. Look for chances to reach multiple enemies.']]]],
[['パペットで遊び方を変える','Puppets that change your approach'],[
['rukiwa',['敵を引きつける白兵パペット。守りを組み立てる楽しさがある一方、修理と再召喚も意識したい編成向け。','A melee puppet draws enemy attention. Build around protection while managing repairs and resummoning.']],
['milena',['遠くの敵へ跳躍するパペットランサー。後衛へ圧力をかける役割を試したい人向け。','A Puppet Lancer can leap toward distant enemies. Try her when you want to pressure the backline.']],
['nonoa',['サポートパペットの回復・支援を活かす編成へ。単純な攻撃役の追加とは違う組み合わせを楽しめます。','Build around a Support Puppet’s healing and utility for a different approach from adding another attacker.']]]]
];return pageHero('recommendations',tr('recommendations'),T(['目的別・編集部おすすめランキング。入手しやすさ、習得スキル、役割の補完を基準にした育成提案です。実戦勝率による最強ランキングではありません。','Purpose-based editorial recommendations, considering availability, skill unlocks and role coverage. These are training suggestions, not win-rate rankings.']))+groups.map(([title,rows])=>section(T(title),rows.map(([id,reason],i)=>{const c=get('characters',id);return `<article class="ranking-row"><div class="ranking-number">${i+1}</div><div class="portrait-wrap">${portrait(c)}</div><div><h3>${link('character',id,L(c.name))} <span class="stars">${'★'.repeat(c.rarity)}</span></h3><p>${T(reason)}</p><small>${esc(L(c.role))} · ${tr(c.acquisition)}</small></div></article>`;}).join(''))).join('')+section(T(['手持ちにいないときは','If you do not own them']),`<p>${T(['同じロールで似たスキルを持つ仲間でも役割を補えます。図鑑で習得Lvと射程を比較し、今いる仲間から編成しましょう。','Other companions with similar roles and skills can fill the gap. Compare unlock levels and range in the catalog and work with your roster.'])}</p><a href="#characters">${tr('characters')} →</a>`);}
function dateJST(t){return new Intl.DateTimeFormat(lang==='ja'?'ja-JP':'en-US',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(t);}
function remaining(t){const m=Math.max(0,Math.ceil((t-Date.now())/60000)),d=Math.floor(m/1440),h=Math.floor(m%1440/60);return T([`終了まで ${d}日 ${h}時間 ${m%60}分`,`Ends in ${d}d ${h}h ${m%60}m`]);}
function featuredCompanion(c,label){return `<a class="card featured-companion" href="${href('character',c.id)}"><div class="portrait-wrap">${portrait(c)}</div><div class="card-body">${tag(label)}<h3>${esc(L(c.name))}</h3><span class="stars">${'★'.repeat(c.rarity)}</span><p>${esc(L(c.description))}</p><span class="feature-link">${T(['この仲間を知る','Meet this companion'])} →</span></div></a>`;}
function liveAdventure(e,now){const d=new Date(now+9*3600000),y=d.getUTCFullYear(),m=e.month-1,start=Date.UTC(y,m,e.half===1?1:16)-9*3600000,end=Date.UTC(y,e.half===1?m:m+1,e.half===1?16:1)-9*3600000;
 const weekly=ratesAt(D,'weekly',now).rows.filter(r=>r.pickup).map(r=>get('characters',r.id)),festivals=['sunday','doubles','seven'].filter(k=>ratesAt(D,k,now).available),cards=D.equipment.filter(c=>c.eventId===e.id&&c.abilityCard);
 return `<div class="section-title"><h2>${tr('current')}</h2><a href="#events">${T(['イベント一覧','All events'])} →</a></div><section class="live-event"><div class="live-event-art">${picture(e.art,L(e.name))}<span class="live-ribbon">${T(['開催中 · 季節の討伐祭','LIVE · SEASONAL EXPEDITION'])}</span></div><div class="live-event-copy"><span class="eyebrow">THIS SEASON’S ADVENTURE</span><h2>${esc(L(e.name))}</h2><p>${esc(L(e.description))}</p><p>${T(['仲間と挑む相手は','Face'])} <strong>${esc(L(e.boss))}</strong>${T(['。',' . '])}${T(['戦いの先に待つ、今回の戦利品を見にいきましょう。','Discover the treasures waiting beyond the battle.'])}</p><a class="button" href="${href('event',e.id)}">${T(['ボスと戦利品を見る','Explore the boss & rewards'])} →</a></div></section><div class="today live-status"><div><small>${T(['開催期間 / 日本時間','Event period / Japan time'])}</small><b>${dateJST(start)} — ${dateJST(end)}</b><small data-countdown="${end}">${remaining(end)}</small></div><div><small>${T(['本日のフェス','Today’s festivals'])}</small><b>${festivals.length?festivals.map(k=>tr(k)).join(' / '):T(['今日は旅支度の日','A day to prepare'])}</b><a href="#summons">${T(['召喚と提供割合を確認','Check summons & rates'])} →</a></div><div><small>${T(['今週のピックアップ','This week’s pickup'])}</small><b>${weekly.map(c=>esc(L(c.name))+' · ★'+c.rarity).join('<br>')}</b><small>${T(['木曜15:00更新 / 日本時間','Refreshes Thursday, 15:00 JST'])}</small></div></div>${cards.length?`<div class="event-rewards"><div><span class="eyebrow">TREASURES TO DISCOVER</span><h3>${T(['今回、手に入れたい一枚。','A card worth the journey.'])}</h3><p>${T(['報酬の効果から、次の編成を考えてみませんか。','Let the rewards inspire your next party.'])}</p></div>${cards.map(c=>`<a class="reward-preview" href="${href('item',c.id)}">${picture(c.art,L(c.name))}<div><strong>${esc(L(c.name))}</strong><p>${esc(L(c.description))}</p></div></a>`).join('')}</div>`:''}<div class="section-title"><h2>${T(['灯がつなぐ、新しい仲間。','New companions by the fire.'])}</h2><a href="#summons">${tr('summons')} →</a></div><div class="split">${featuredCompanion(get('characters',e.characterId),tr('limited'))}${featuredCompanion(weekly[0],tr('weekly'))}${festivals.map(k=>featuredCompanion(get('characters',ratesAt(D,k,now).rows.find(r=>r.pickup).id),tr(k))).join('')}</div><section class="journey-note"><span class="eyebrow">YOUR ADVENTURE, YOUR PACE</span><h2>${T(['冒険は、あなたのペースで。','Adventure at your own pace.'])}</h2><p>${T(['強敵に挑む日も、焚き火のそばで仲間を育てる日も。装備をひとつ替えたり、新しいカードを組み合わせたり、小さな旅支度が次の勝利につながります。','Some days are for mighty foes; others are for preparing by the fire. A new piece of gear or a different card can open the way to your next victory.'])}</p><p>${T(['一度クリアしたダンジョンは、前回の編成でバックグラウンド探索も可能です。仲間に探索を任せて、物語を進めたり、別の仲間とイベントに挑んだり。あなたらしい旅を見つけましょう。','Cleared dungeons can be explored in the background with your last successful party. While they travel, continue the story or join an event with another companion. Find your own way to adventure.'])}</p><a href="#guide">${T(['次の冒険のヒントを読む','Find inspiration for your next journey'])} →</a></section>`;}
function home(){const now=new Date(Date.now()+9*3600000),e=D.events.find(e=>e.month===now.getUTCMonth()+1&&e.half===(now.getUTCDate()<16?1:2));return `<div class="crumb">${tr('subtitle')}</div><section class="hero">${picture(D.hero,tr('intro'))}<div class="hero-copy"><span class="eyebrow">CAMPFIRE TACTICS · FIELD GUIDE</span><h1>${tr('intro')}</h1><p>${tr('introText')}</p><a class="button" href="#characters">${tr('browse')} →</a></div></section><div class="today">${[[D.characters.length,'characters'],[D.equipment.filter(c=>c.abilityCard).length,'cardCatalog'],[D.events.length,'events']].map(([n,k])=>`<div><small>${tr(k)}</small><b>${n}</b></div>`).join('')}</div>${adventureHub()}${liveAdventure(e,Date.now())}<div class="section-title"><h2>${tr('new')}</h2><a href="#cards">${tr('cards')} →</a></div><div class="grid wide">${D.equipment.filter(c=>c.permanentQuest).filter((_,i)=>[0,15,30].includes(i)).map(itemCard).join('')}</div><div class="section-title"><h2>${tr('characters')}</h2><a href="#characters">${tr('all')} →</a></div><div class="grid">${['kai','rukiwa','milena','nonoa'].map(id=>charCard(get('characters',id))).join('')}</div>`;}
function filters(extra=''){return `<div class="filterbar"><input id="query" type="search" placeholder="${tr('query')}" aria-label="${tr('query')}">${extra}</div><p id="count" class="count" aria-live="polite"></p><div id="listing"></div><div id="pagination" class="pagination"></div>`;}
const select=(id,label,options)=>`<select id="${id}" aria-label="${esc(label)}"><option value="">${esc(label)} · ${tr('all')}</option>${options.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select>`;
const raritySelect=()=>select('rarity',tr('rarity'),[3,4,5].map(n=>[n,'★'+n]));
function listPage(kind){let extra='';if(kind==='characters')extra=select('role',tr('role'),[...new Set(D.characters.map(c=>c.role.ja))].map(r=>[r,L(D.characters.find(c=>c.role.ja===r).role)]))+raritySelect()+select('element',tr('element'),['fire','water','wind','light','dark'].map(e=>[e,element(e)]));if(kind==='equipment')extra=select('slot',tr('equipment'),['weapon','armor','accessory'].map(s=>[s,tr(s)]));if(kind==='cards')extra=raritySelect()+select('origin',tr('acquisition'),['permanent','event','legacy'].map(x=>[x,tr(x)]));if(kind==='story')extra=select('arc',tr('story'),[0,1,2].map(n=>[n,tr('chapter'+n)]));if(kind==='dungeons')extra=select('rank',tr('rank'),D.ranks.map(r=>[r.name,r.name]));let note=kind==='equipment'?T(['旧装備も掲載しています。図鑑への掲載は現在の入手可能性を保証しません。','Legacy gear is included. A listing does not guarantee current availability.']):kind==='story'?tr('spoiler'):kind==='skills'?tr('skillNote'):'';return pageHero(kind,tr(kind),note)+(['dungeons','quests','events','story','cards','camp'].includes(kind)?`<div class="highlight"><a href="#${({dungeons:'dungeon-guide',quests:'quest-guide',events:'event-guide',story:'story-guide',cards:'cards-guide',camp:'camp-guide'})[kind]}">${T(['遊び方と攻略のヒントを読む','Read the guide & strategy tips'])} →</a></div>`:'')+(['quests','dungeons','cards','events','camp'].includes(kind)?intro(kind):'')+filters(extra);}
function intro(kind){const notes={quests:[['通常依頼はスタミナ1・最大3フェーズ。報酬アクセサリは生成時に50％で設定され、事前に確認できます。','Ordinary quests cost 1 stamina, last up to 3 phases, and have a 50% chance to offer a visible accessory reward.'],['恒常カード依頼は独立した2枠で各10％の登場抽選。出現後はクリアまで残り、専用カードを1枚獲得できます。','Permanent card quests use two independent slots, each rolling 10%. Once posted, they remain until cleared and award their specific card.']],dungeons:[['前回のクリア編成・時間を記録した依頼は、追加スタミナ1でバックグラウンド探索が可能です。難易度別の依頼は別IDで記録されます。','Quests with a recorded clear party and time allow background exploration for 1 extra stamina. Difficulty-specific quests keep separate records.']],cards:[['パーティ効果と装備者効果を確認しましょう。同じパーティ補正は加算ではなく最大値です。恒常カードは特定ロール・武器・パペット向けの控えめな特化性能です。','Check both party and wearer effects. Matching party modifiers use the maximum value, not their sum. Permanent cards offer modest specialization for roles, weapons and puppets.']],events:[['毎月1〜15日・16日〜月末の2期間、年間24イベント。ソロはスタミナ1、共闘は2。期間は日本時間です。','Two periods each month: days 1–15 and 16–month end, for 24 events annually. Solo costs 1 stamina; co-op costs 2. Dates use Japan time.']],camp:[['キャンプ道具は最大2個を装備可能。掲載の抽選確率は対応するレア度の道具抽選時の値です。','Equip up to two camp tools. Listed probabilities apply when rolling the corresponding tool rarity.']]};return `<div class="highlight">${notes[kind].map(p=>`<p>${esc(T(p))}</p>`).join('')}</div>`+(kind==='quests'?`<details class="panel"><summary>${T(['特殊依頼のEXP・Gold倍率','Special quest EXP and gold multipliers'])}</summary>${table([tr('name'),'EXP','Gold'],D.specialQuests.map(q=>[esc(L(q.name)),'×'+q.xp,'×'+q.gold]))}</details>`:'');}
function renderList(kind){const query=($('#query')?.value||'').trim().toLocaleLowerCase(),val=id=>$('#'+id)?.value||'';let items=kind==='cards'?D.equipment.filter(e=>e.abilityCard):kind==='equipment'?D.equipment.filter(e=>e.slot!=='card'):D[kind==='story'?'missions':kind];items=items.filter(x=>(!query||[x.id,L(x.name),L(x.description)].join(' ').toLocaleLowerCase().includes(query))&&(!val('role')||x.role.ja===val('role'))&&(!val('rarity')||(x.rarity||x.tier)===+val('rarity'))&&(!val('element')||x.element===val('element'))&&(!val('slot')||x.slot===val('slot'))&&(!val('rank')||x.rank===val('rank'))&&(!val('arc')||x.arc===+val('arc'))&&(!val('origin')||(x.permanentQuest?'permanent':x.eventId?'event':'legacy')===val('origin')));const max=Math.max(1,Math.ceil(items.length/36));page=Math.min(max,page);$('#count').textContent=items.length+tr('count')+' · '+page+' / '+max;const rows=items.slice((page-1)*36,page*36);let html='';if(kind==='characters')html=`<div class="grid">${rows.map(charCard).join('')}</div>`;else if(kind==='cards')html=`<div class="grid wide">${rows.map(itemCard).join('')}</div>`;else if(kind==='events')html=`<div class="grid wide">${rows.map(eventCard).join('')}</div>`;else if(kind==='quests')html=`<div class="grid wide">${rows.map(q=>`<a class="card" href="${href('quest',q.id)}">${picture(get('equipment',q.cardId).art,L(q.name))}<div class="card-body">${tag('Lv.'+q.level)}${tag(q.phases+' '+tr('phases'))}<h3>${esc(L(q.name))}</h3><p>${esc(L(get('equipment',q.cardId).name))}</p></div></a>`).join('')}</div>`;else{const type={equipment:'item',skills:'skill',story:'mission',dungeons:'dungeon',camp:'tool'}[kind];html=table([tr('name'),kind==='story'?tr('recommended'):kind==='dungeons'?tr('rank'):tr('effect')],rows.map(x=>[link(type,x.id,L(x.name)),kind==='story'?`Lv.${x.level} · ${tr('chapter'+x.arc)} · ${x.phases} ${tr('phases')}`:kind==='dungeons'?`${x.rank} / ${x.difficulty||'—'} · ${x.floors} ${tr('floors')}`:esc(L(x.description)||statText(x.stats))]));}$('#listing').innerHTML=rows.length?html:`<p class="empty">${tr('empty')}</p>`;$('#pagination').innerHTML=`<button class="button" data-page="${page-1}" ${page===1?'disabled':''}>${tr('previous')}</button><span>${page} / ${max}</span><button class="button" data-page="${page+1}" ${page===max?'disabled':''}>${tr('next')}</button>`;$('#pagination').onclick=e=>{const b=e.target.closest('[data-page]');if(b){page=+b.dataset.page;renderList(kind);$('#count').scrollIntoView({block:'start'});}};}
function statText(s){return Object.entries(s||{}).map(([k,v])=>(k==='cast'?tr('statcast'):k.toUpperCase())+' '+(v>=0?'+':'')+v).join(' / ');}
function characterDetail(c){return `<div class="detail-hero"><div class="portrait-wrap">${portrait(c)}</div><div class="body">${tag('★'+c.rarity)}${tag(L(c.role))}${tag(element(c.element))}${heading(L(c.name),L(c.title))}<p>${esc(L(c.description))}</p><p>${tr('acquisition')}：${tr(c.acquisition==='story'?'storyOnly':c.acquisition)}</p></div></div>${section(tr('baseline'),`<div class="stat-grid">${Object.entries(c.stats).map(([k,v])=>`<div class="stat"><small>${k.toUpperCase()}</small><b>${v}</b></div>`).join('')}</div>`)}${section(tr('skills'),`<p class="note">${tr('skillNote')}</p>`+table([tr('learn'),tr('name'),tr('effect')],c.skills.map(s=>{const skill=get('skills',s.id);return[s.level,link('skill',s.id,L(skill.name)),esc(L(skill.description))];})))}${section(tr('abilities'),table([tr('learn'),tr('name'),tr('effect')],c.abilities.map(a=>[a.level,esc(L(a.name)),esc(L(a.description))])))}`;}
function itemDetail(c){const q=D.quests.find(q=>q.cardId===c.id);return `<div class="detail-hero">${c.art?picture(c.art,L(c.name),'detail-art'):''}<div class="body">${tag(tr(c.slot))}${tag('★'+(c.tier||'—'))}${heading(L(c.name))}<p>${esc(L(c.description)||tr('noDescription'))}</p><p>${esc(statText(c.stats))}</p>${c.roles?`<p>${tr('role')}：${esc(c.roles.map(r=>D.characters.find(c=>c.role.ja===r)?.role[lang]||r).join(' / '))}</p>`:''}</div></div>${q?section(tr('acquisition'),link('quest',q.id,L(q.name))):c.eventId?section(tr('acquisition'),link('event',c.eventId,L(get('events',c.eventId)?.name))):''}`;}
function skillDetail(s){return heading(L(s.name))+section(tr('effect'),`<p>${esc(L(s.description))}</p><p class="note">${tr('skillNote')}</p>`)+table(['MP',tr('range'),tr('area'),tr('ct'),tr('uses'),tr('power')],[[s.mp,s.range,s.area?esc((s.areaShape==='cross'?tr('cross'):tr('radius'))+' '+s.area):tr('single'),s.jumpCT||s.cast||tr('instant'),s.uses,s.power||'—']])+section(tr('characters'),D.characters.filter(c=>c.skills.some(x=>x.id===s.id)).map(c=>link('character',c.id,L(c.name))).join(' / '));}
function questDetail(q){const c=get('equipment',q.cardId);return heading(L(q.name),L(q.description))+table([tr('recommended'),tr('phases'),tr('stamina'),tr('xp'),tr('gold')],[[q.level,q.phases,q.stamina,q.xp,q.gold]])+section(tr('reward'),`<div class="grid wide">${itemCard(c)}</div>`)+q.stories[lang].map((lines,i)=>`<details class="panel"><summary>${tr(i?'after':'before')}</summary>${lines.map(l=>`<p>${l.speaker?`<b>${esc(l.speaker)}：</b>`:''}${esc(l.text)}</p>`).join('')}</details>`).join('');}
function dungeonDetail(q){return heading(L(q.name),L(q.description))+table([tr('rank'),tr('difficulty'),tr('floors'),tr('stamina')],[[q.rank,q.difficulty||'—',q.floors,q.stamina]])+section(tr('reward'),`<p>EXP ${q.rewards.xp} / G ${q.rewards.gold} / RP ${q.rewards.rp}</p>${q.reward?`<p>${esc(L(q.reward))}</p>`:''}`)+intro('dungeons');}
function eventDetail(e){return picture(e.art,L(e.name),'art-full')+heading(L(e.name),L(e.description))+section(tr('schedule'),`<p>${e.month} / ${tr(e.half===1?'firstHalf':'secondHalf')} · JST</p><p>${tr('boss')}：${esc(L(e.boss))}</p><p>${tr('featured')}：${link('character',e.characterId,L(get('characters',e.characterId).name))}</p>`)+table([tr('rank'),tr('difficulty'),tr('recommended'),tr('xp'),tr('gold'),tr('chance')],e.stages.map(s=>[D.ranks[s.rank].name,['Easy','Normal','Hard','Very Hard','Hell'][s.difficulty],s.level,s.xp,s.gold,+(D.chestChance[s.difficulty]*100).toFixed(2)+'%']))+`<p class="note">${T(['確率はイベントボス宝箱の基礎出現率。キャンプ道具などの補正前です。','Probability is the base event boss chest appearance rate, before camp tool modifiers.'])}</p>`+section(tr('cards'),`<div class="grid wide">${D.equipment.filter(c=>c.eventId===e.id&&c.abilityCard).map(itemCard).join('')}</div>`);}
function missionDetail(m){return heading(L(m.name),L(m.description))+table([tr('story'),tr('recommended'),tr('phases'),tr('goal')],[[tr('chapter'+m.arc),m.level,m.phases,esc(L(m.goal))]])+section(tr('enemy'),table([tr('name'),tr('role'),tr('skills')],m.enemies.map(e=>[esc(L(e.name)),esc(L(e.role)),e.skills.map(id=>link('skill',id,L(get('skills',id)?.name)||id)).join(' / ')])));}
function guide(kind){const g=guides[kind];return pageHero(kind,tr(kind))+g.sections.map(([title,body,tip])=>section(T(title),`${tag(tr(tip?'tip':'fact'))}<p>${esc(T(body))}</p>`)).join('')+(kind==='growth'?section(tr('rank'),table([tr('rank'),'RP'],D.ranks.map(r=>[r.name,r.points]))):'');}
function summons(){const date=new Date(Date.now()+9*3600000).toISOString().slice(0,16);return heading(tr('summons'))+`<div class="highlight">${T(['★5：5％ / ★4：30％ / ★3：65％。ピックアップ対象はそのレア度枠の50％。全キャラの確率を下に表示します。','★5: 5% / ★4: 30% / ★3: 65%. Featured characters receive 50% of their rarity bucket. Individual rates are listed below.'])}</div><div class="filterbar"><label>${tr('date')} <input type="datetime-local" id="rate-date" value="${date}"></label><select id="banner" aria-label="${tr('summons')}">${['normal','weekly','limited','sunday','doubles','seven'].map(b=>`<option value="${b}">${tr(b)}</option>`).join('')}</select></div><p class="note">${tr('ratesNote')}</p><div id="rates"></div>`;}
function renderRates(){const now=Date.parse($('#rate-date').value+':00+09:00');if(!Number.isFinite(now))return;const result=ratesAt(D,$('#banner').value,now);$('#rates').innerHTML=!result.available?`<p class="empty">${tr('closed')}</p>`:`<p>${tr('total')}：${(result.rows.reduce((n,r)=>n+r.probability,0)*100).toFixed(6)}%</p>`+table([tr('name'),tr('rarity'),tr('probability'),tr('featured')],result.rows.map(r=>[link('character',r.id,L(get('characters',r.id).name)),'★'+r.rarity,(r.probability*100).toFixed(6)+'%',r.pickup?'★':'—']));}
function about(){return heading(tr('about'))+section(T(['この攻略Wikiについて','About this guide']),`<p>${T(['仲間との出会い、装備選び、強敵との戦い。次の冒険が楽しみになる情報を集めた攻略Wikiです。','A guide to companions, equipment, and challenging foes, made to inspire your next adventure.'])}</p><p>${tr('dataNote')}</p>`);}

function search(q){const groups=[['characters','character'],['equipment','item'],['skills','skill'],['quests','quest'],['missions','mission'],['dungeons','dungeon'],['events','event'],['camp','tool']],needle=q.toLocaleLowerCase();const results=needle?groups.flatMap(([g,type])=>D[g].filter(x=>[L(x.name),L(x.description),x.id].join(' ').toLocaleLowerCase().includes(needle)).map(x=>({x,type,g}))):[];return heading(tr('results'),q)+`<p>${results.length}${tr('count')}</p>`+table([tr('name'),tr('effect')],results.slice(0,200).map(({x,type,g})=>[link(type,x.id,L(x.name)),esc(L(x.description)).slice(0,180)]))+(!results.length?`<p class="empty">${tr('empty')}</p>`:'');}
function render(){page=1;document.documentElement.lang=lang;$('#language').value=lang;$('#brand').innerHTML=tr('brand')+`<small>${tr('subtitle')}</small>`;$('#global-search').placeholder=tr('search');$('#navlabel').textContent=tr('nav');$('#aside-note').textContent=tr('quiet');$('#footer').innerHTML=`${tr('brand')} · ${tr('subtitle')}<span>${tr('dataNote')}</span><span>${tr('foot')}</span>`;const [kind='home',...rest]=(location.hash.slice(1)||'home').split('/');let id;try{id=decodeURIComponent(rest.join('/'));}catch{id='';}$('#navigation').innerHTML=nav.map((n,i)=>`<a href="#${n}" ${n===kind?'aria-current="page"':''}>${icons[i]}　${tr(n)}</a>`).join('')+`<p class="navlabel">${T(['遊び方と特集','Guides & features'])}</p>`+['story-guide','dungeon-guide','quest-guide','event-guide','coop-guide','cards-guide','camp-guide','background-guide','friends-guide','growth-guide','recommendations','schedule'].map(k=>`<a href="#${k}" ${kind===k?'aria-current="page"':''}>${esc(tr(k).split(' ― ')[0].split(' — ')[0])}</a>`).join('');let html;if(kind==='home')html=home();else if(articles[kind])html=articlePage(kind);else if(kind==='schedule')html=schedulePage();else if(kind==='recommendations')html=recommendationsPage();else if(guides[kind])html=guide(kind);else if(['characters','skills','equipment','cards','quests','dungeons','events','story','camp'].includes(kind))html=listPage(kind);else if(kind==='summons')html=summons();else if(kind==='about')html=about();else if(kind==='search')html=search(id);else if(kind==='main'){html=home();}else{const map={character:['characters',characterDetail],item:['equipment',itemDetail],skill:['skills',skillDetail],quest:['quests',questDetail],dungeon:['dungeons',dungeonDetail],event:['events',eventDetail],mission:['missions',missionDetail],tool:['camp',c=>heading(L(c.name))+section(tr('effect'),`<p>${esc(L(c.description))}</p><p>★${c.tier} · ${tr('chance')} ${+(c.chance*100).toFixed(4)}%</p>`)]};const spec=map[kind],data=spec&&get(spec[0],id);html=data?`<div class="crumb">${link(spec[0]==='missions'?'story':spec[0],null,tr('back'))}</div>`+spec[1](data):heading(tr('notfound'));}$('#main').innerHTML=html;document.title=($('#main h1')?.textContent||tr(kind))+' | '+tr('brand')+' Wiki';if($('#listing')){renderList(kind);$('.filterbar').oninput=()=>{page=1;renderList(kind);};$('.filterbar').onchange=()=>{page=1;renderList(kind);};}if(kind==='summons'){$('#banner').onchange=renderRates;$('#rate-date').onchange=renderRates;renderRates();}}
$('#language').onchange=()=>{lang=$('#language').value;const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);render();};$('#searchform').onsubmit=e=>{e.preventDefault();location.hash='search/'+encodeURIComponent($('#global-search').value.trim());};window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
try{const response=await fetch('data/game.json?v=20260921-adventure');if(!response.ok)throw Error('HTTP '+response.status);D=await response.json();render();}catch(error){$('#main').innerHTML='<h1>データを読み込めません / Unable to load data</h1><p>'+esc(error.message)+'</p>';}

setInterval(()=>{document.querySelectorAll('[data-countdown]').forEach(el=>el.textContent=remaining(+el.dataset.countdown));},60000);

document.addEventListener('click',e=>{const a=e.target.closest('[data-section]');if(a){e.preventDefault();document.getElementById(a.dataset.section)?.scrollIntoView({block:'start',behavior:'smooth'});}});
