// Player-facing editorial guides. Order is title, introduction, sections, related destinations.
export const articles={
'story-guide':{
 title:['ストーリー攻略 ― 焚き火から、最後の戦いへ','Story guide — From the fire to the final battle'],
 intro:['カイたちの旅を、ひとつずつ。行き詰まったときは、レベルだけでなく「誰を先に倒すか」を見直してみましょう。','Follow Kai’s journey one chapter at a time. When a battle stalls, reconsider your target priorities as well as your levels.'],
 sections:[
 [['プロローグ：5人の役割を覚える','Prologue: learn your party’s roles'],['前衛が敵を受け止め、後衛が攻撃と回復を支える形を練習しましょう。全員を敵に近づけるより、回復役の安全と射程を確保する方が立て直しやすくなります。','Practice letting the frontline absorb pressure while ranged units attack and heal. Keeping your healer safe and within range makes recovery easier than rushing everyone forward.']],
 [['第一章：装備を整えながら旅を進める','Chapter I: grow into your equipment'],['勝てなくなったらダンジョンで武器・防具を更新し、依頼で役割に合うアクセサリを探しましょう。最強装備の一括更新後も、MOVE・SPD・カードの対象条件は確認しておきたいポイントです。','If progress slows, improve weapons and armor in dungeons and look for suitable quest accessories. After using Best Gear, still review MOVE, SPD and card conditions.']],
 [['第二章：後衛を放置しない','Chapter II: pressure enemy supports'],['10話以降のデバッファーは毒・睡眠・麻痺・スタン、15話以降のヒーラーはHP25%の範囲蘇生を使います。状態異常を受ける前に妨害役へ届く射程を用意し、蘇生役を残して同じ敵を何度も倒す展開を避けましょう。','From episode 10, debuffers use poison, sleep, paralysis and stun. From episode 15, healers can revive units with 25% HP in an area. Bring range to pressure supports and avoid repeatedly defeating enemies while their healer remains.']],
 [['終盤の旅支度：23話と24話','Preparing for episodes 23 and 24'],['23話は推奨Lv40・10階層、24話は推奨Lv45・5フェーズです。短期決戦だけでなく、MP・スキル回数を保つキャンプ道具や回復役を意識しましょう。詳しい敵情報はストーリー一覧から各話へ進んで確認できます。','Episode 23 recommends Lv40 and spans 10 floors; episode 24 recommends Lv45 and has 5 phases. Plan for MP, skill uses and sustained healing. Open each episode in the story list for its enemies.']]],links:['story','combat','camp-guide']},
'dungeon-guide':{title:['ダンジョン攻略 ― 次の一本を探す旅','Dungeon guide — The hunt for your next weapon'],intro:['強い装備を探すだけでなく、踏破した編成を育てて探索を任せる楽しみもあります。まずは安定して帰ってこられる5人を作りましょう。','Build a reliable five-person party, discover new gear, and eventually send your proven team out on background expeditions.'],sections:[
 [['目的を決めて出撃する','Choose your goal first'],['武器・防具・既存アクセサリを集めたいときはダンジョンへ。依頼詳細の階層数や報酬を確認し、無理なく踏破できる行き先を選ぶと装備を揃えやすくなります。','Dungeons offer weapons, armor and existing accessories. Check the floor count and rewards and choose a destination your party can reliably clear.']],
 [['番人の前に、消耗を抑える','Conserve resources before the guardian'],['通常探索では5階層ごとにボスが現れます。道中の敵に高コストスキルを使い切らず、残りMPと使用回数を確認しながら進みましょう。階層間の回復に役立つキャンプ道具も長期戦向きです。','Regular expeditions feature a boss every five floors. Track MP and remaining skill uses instead of spending everything on early enemies. Camp tools that recover resources between floors help sustain long runs.']],
 [['金のトカゲを見かけたら','When the golden lizard appears'],['金のトカゲ依頼はEXP・Gを狙える特別な探索先です。同じ深さの基礎報酬に対してEXP3倍・G5倍。通常装備の収集とは目的を分け、育てたい仲間と装備を整えて挑みましょう。','Golden-lizard expeditions award 3× EXP and 5× gold relative to the base depth reward. Treat them as a growth opportunity rather than a regular gear run, and prepare the companions you want to train.']],
 [['前回の成功を、次の探索につなげる','Turn a successful clear into an expedition'],['一度クリアした依頼では、前回クリアした編成・時間を使ってバックグラウンド探索ができます。スタミナは通常出撃より1多く、編成が前回のものへ切り替わります。出発前に記録と拘束される仲間を確認しましょう。','Cleared requests can use the last successful party and clear time for background exploration. It costs one extra stamina and switches to the recorded party. Review the saved team before committing.']]],links:['dungeons','background-guide','camp-guide']},
'quest-guide':{title:['クエスト攻略 ― 掲示板で見つける小さな物語','Quest guide — Small stories on the notice board'],intro:['報酬だけでなく、依頼者の困りごとや仲間との会話も旅の一部。気になる依頼と、育てたい役割に合う報酬を探しましょう。','Requests offer more than rewards: meet travelers, hear their stories, and find gear suited to the roles you want to develop.'],sections:[
 [['通常依頼でアクセサリを集める','Collect accessories through ordinary requests'],['通常依頼はスタミナ1。50%の確率でアクセサリ報酬が設定され、出発前に何がもらえるか確認できます。報酬は依頼Lvに合う帯から選ばれるので、欲しい効果と挑める難易度を見比べましょう。','Ordinary requests cost 1 stamina. There is a 50% chance for an accessory reward to be assigned and shown before departure. Its tier follows the request level: compare useful effects with a manageable challenge.']],
 [['45枚の恒常カードは、使いどころを探す収集','Find a purpose for each of the 45 permanent cards'],['恒常カードは、イベントカードより控えめな特化型です。パペット、武器、ロールなどの条件が合う編成で活かしましょう。専用依頼は登場後クリアまで残り、失敗・撤退後も再挑戦できます。','Permanent cards offer modest specialization compared with event cards. Match puppet, weapon and role conditions to your party. Once their dedicated requests appear, they remain until cleared and can be retried after defeat or retreat.']],
 [['掲示の更新と危険表示を見る','Watch the board and danger labels'],['ダンジョン・イベントのクリア、クエストのクリア・失敗でゲーム内の日付と掲示が進みます。赤い「危険」は平均Lvを超える依頼などの目安です。報酬だけで決めず、敵・護衛条件・フェーズ数も確認しましょう。','Dungeon and event clears, and quest clears or failures, advance the in-game date and board. A red danger label flags requests such as those above your average level. Check enemies, escort conditions and phases as well as rewards.']],
 [['クエスト限定のお宝を見逃さない','Look beyond ordinary rewards'],['依頼でしか手に入らないアクセサリ、アビリティカード、キャンプ道具があります。掲示の上部に並ぶレア依頼も確認し、気になる報酬は期限が切れる前に挑戦しましょう。','Some accessories, cards and camp tools are quest exclusives. Check the rare requests at the top of the board and tackle appealing rewards before they expire.']]],links:['quests','cards','equipment']},
'event-guide':{title:['イベント攻略 ― 季節のボスと戦利品','Event guide — Seasonal bosses and treasures'],intro:['半月ごとに変わる冒険先。今回のボス、欲しいカード、挑むランクを決めるところから始めましょう。','Every half-month brings a different destination. Start with the boss, the cards you want, and a rank your party can handle.'],sections:[
 [['開催は毎月2回、日本時間で切り替わる','Two events each month, on Japan time'],['1日〜15日、16日〜月末の2期間で、年間24種類のイベントがあります。期間限定召喚の仲間も開催中のイベントと連動します。トップの開催期間と召喚カレンダーを旅の目印にしてください。','Events run on days 1–15 and 16–month end, for 24 themes annually. The limited summon companion follows the current event. Use the home page and summon calendar to plan your journey.']],
 [['仲間とボスに挑む','Challenge the boss with companions'],['「仲間と攻略」はスタミナ2。自分の参加キャラクターを中心に仲間と戦い、宝箱の戦利品をダイス順で分け合います。狙った品を必ず持ち帰れるわけではないので、分配のルールも確認しましょう。','Co-op costs 2 stamina and centers on your participant and shared loot is drafted in dice order. Read the distribution rules before setting your sights on a particular reward.']],
 [['高い難易度は、報酬と安定性のバランス','Balance reward quality with reliability'],['ランクと難易度で敵のLv・EXP・G・宝箱の基礎出現率が変わります。背伸びして全滅するより、安定してクリアできる段階からカードや装備を揃えて次へ進むのがおすすめです。','Rank and difficulty change enemy levels, EXP, gold and base chest rates. Building up gear through reliable clears is often a better starting point than repeatedly losing on a harder setting.']],
 [['SPD装備も注目の戦利品','Watch for speed accessories'],['イベント宝箱が出た後のSPDアクセサリ抽選は、共闘で20%です。共闘で出現しても、ダイス順に選ぶため獲得確定ではありません。編成の行動順を調整したいときの収集目標になります。','After an event chest appears, the speed-accessory roll is 20% in co-op. Appearing in a shared chest does not guarantee you receive it: draft order still applies. These items are goals for turn-order tuning.']]],links:['events','coop-guide','schedule']},
'coop-guide':{title:['共闘とロットダイス ― 仲間と勝って、戦利品を選ぶ','Co-op & loot dice — Win together, choose your prize'],intro:['戦いのあとにも、もうひとつの楽しみ。フレンドの冒険者カードで仲間を迎え、ダイスで戦利品を選ぶ順番を決めます。','The adventure continues after victory. Recruit companions through friend adventurer cards, then roll to decide the loot draft order.'],sections:[
 [['友達が同時に操作しなくても遊べる','Friends do not need to be online together'],['共闘はフレンドの冒険者カードやNPCを使う方式です。リアルタイムで同時操作する通信対戦ではありません。自分のリーダーが通常の参加者になり、背景探索中は未編成のサブリーダーを選べます。','Co-op uses friend adventurer cards and NPCs rather than live simultaneous controls. Your leader normally joins; during a background expedition, choose an unassigned subleader.']],
 [['宝箱を開けたら、全員がダイス','Everyone rolls after opening the chest'],['基本の出目は1〜100。大きい人から残った戦利品を1つ選びます。同点の場合の順番は抽選です。自分の番までに欲しい品が選ばれる場合もあるので、第2候補も考えておきましょう。','Base rolls range from 1 to 100. Higher results choose one remaining item first; ties are randomly ordered. Have a second choice ready in case your favorite is taken.']],
 [['イカサマ道具で、運を少し味方に','Give luck a little nudge'],['勝利のお守りは+5、イカサマダイスは+10、詐欺師のダイスは+15、八百長ダイスは+20。装備した道具の加算は自分の出目に反映されます。キャンプ道具は初期2枠、ストーリー進行で3枠になるので、回復や宝箱補正との選択も楽しみどころです。','Victory Charm adds 5, Loaded Dice 10, Trickster Dice 15 and Rigged Dice 20 to your roll when equipped. With two camp-tool slots initially and a third unlocked through the story, you must weigh better rolls against recovery and chest bonuses.']],
 [['最後まで分配を受け取る','Finish the distribution'],['ダイスを振る前にアプリを閉じると、その抽選は無効になります。討伐EXPやGは受け取れますが、戦利品の分配は最後まで進めましょう。ダイス後に読み直しても出目のやり直しにはなりません。','Closing the app before rolling voids that loot drawing, though battle EXP and gold remain awarded. Finish the distribution; reloading after rolling does not reroll the result.']]],links:['friends-guide','camp-guide','event-guide']},
'cards-guide':{title:['カード収集とビルド ― 一枚から編成が変わる','Cards & builds — One card can change your party'],intro:['同じ仲間でも、カードの組み合わせで役割が変わります。数値の大きさだけでなく、誰に・いつ効くかを読み解きましょう。','A different card can change what a familiar companion brings to battle. Read who benefits and when, not just the size of the number.'],sections:[
 [['パーティ効果と装備者効果を分けて読む','Read party and wearer effects separately'],['全味方・特定属性への補正と、装備者だけへの補正は対象が違います。ロールや武器種の条件がある効果は、条件に合う仲間に装備させて初めて活かせます。','Party-wide or elemental bonuses differ from wearer-only effects. Role and weapon conditions need a matching wearer to deliver their benefit.']],
 [['同じパーティ補正は合算しない','Matching party bonuses do not add together'],['同じパーティ補正は最大値が使われます。似たカードを重ねる前に、攻撃・防御・回復など別の不足を補えるカードがないか比べましょう。','Matching party modifiers use the highest value. Before stacking similar cards, consider covering a different need such as offense, defense or healing.']],
 [['恒常カードは特化、イベントカードは大きな目標','Specialize with quests; aim higher with events'],['45枚の恒常カードには、パペットや特定の武器・ロール向けの使い道があります。イベントカードは季節ごとの収集目標。攻略する場所に合わせて付け替えると、控えめな効果でも働く場面が見つかります。','The 45 permanent cards include puppet, weapon and role specializations. Seasonal event cards provide longer-term collection goals. Switch cards to suit the encounter and even modest effects can find a useful niche.']],
 [['まずは一つ、試したい編成を決める','Choose one build to try'],['パペットを支える編成、回復役を守る編成、属性を揃える編成など、ひとつの目的からカードを探すと選びやすくなります。カード図鑑の効果検索で、使いたいロールや能力を調べてみましょう。','Start with one idea: supporting puppets, protecting your healer, or matching elements. Search the card catalog for the role or stat your build needs.']]],links:['cards','quest-guide','recommendations']},
'camp-guide':{title:['キャンプ道具 ― 出発前の道具選びに作戦を込める','Camp tools — Prepare your tools for the journey'],intro:['キャンプ道具は初期では2個までセットでき、ストーリーを進めると3個までセットできます。道具は長い探索や戦利品選びを助けてくれます。今日の行き先に合わせて旅支度を。','Initially, you can equip two camp tools; story progress unlocks a third slot. Tools support long expeditions and improve your loot chances. Prepare for the journey you are taking today.'],sections:[
 [['長期探索なら、階層間の回復','Recovery for long expeditions'],['保温マグボトルはHP/MP10%とスキル回数1、ウォーターサーバーは20%と2、生命維持装置は30%と3をフェーズ・階層クリア時に回復します。一戦限りのスキルなど、回復対象外もあります。','At phase or floor clears, the insulated mug restores 10% HP/MP and 1 skill use, the water server 20% and 2, and life support 30% and 3. Some skills, including once-per-battle skills, are excluded.']],
 [['育成したい日は、EXPを助ける道具','Tools for a training day'],['たこ焼き機は戦闘クリアEXP+10%、幸せホットメーカーは+20%。育てたい仲間を連れて、踏破できる場所に挑むときの候補です。','The takoyaki maker adds 10% battle-clear EXP; the happy hot maker adds 20%. Consider them when taking developing companions on manageable runs.']],
 [['共闘のお楽しみは、ダイスか宝箱か','Dice or chests for co-op?'],['ダイス系は戦利品の選択順を助け、お守り系はイベント宝箱の出現を助けます。祝福お守りには宝箱4枠目の出現率+25%もあります。所持する道具と欲しい報酬に合わせて道具を選びましょう。','Dice tools help draft order, while charms improve event chest appearance. Blessed Charm also adds 25% to the fourth-item chance. Choose your tools around your collection and reward goals.']],
 [['冒険の合間にも、小さな助け','Small comforts between adventures'],['スタミナは基本10分で1回復。ケバブ焼き機は30秒短縮、神々の饗宴鍋は30秒短縮に加えてイベントボス宝箱出現率+10%。戦闘準備だけでなく、遊ぶペースに合わせた選び方もできます。','Base stamina recovery is one every 10 minutes. The kebab grill reduces that by 30 seconds; the divine feast pot does the same and adds 10% event boss chest chance. Tool choices can suit your pace as well as your battles.']]],links:['camp','coop-guide','dungeon-guide']},
'background-guide':{title:['バックグラウンド探索 ― 仲間に任せる冒険','Background exploration — An expedition you can leave to your party'],intro:['一度勝ち取った踏破記録が、次の冒険を助けてくれます。探索班とイベントに行く仲間を分けてみましょう。','A successful clear becomes the basis of future expeditions. Plan an exploration team and a separate event companion.'],sections:[
 [['まずは一度、通常出撃でクリア','First, clear it normally'],['未クリアの依頼では利用できません。前回のクリア編成・時間が記録されている依頼を選ぶと、その編成へ切り替えて出撃します。スタミナは通常コスト+1です。','This is unavailable before a clear. Select a request with a recorded party and clear time; departure switches your party to that lineup and costs one extra stamina.']],
 [['所要時間は前回のクリア時間','It takes as long as your last clear'],['アプリを閉じていても進行します。出発前に記録を見て、いつ戻るかを確認しましょう。完了後は「結果を見る」からリザルトを開きます。','Progress continues while the app is closed. Check the recorded duration before departure, then use View Results when the expedition completes.']],
 [['待っている間に、別の冒険へ','Try another adventure while you wait'],['探索中の編成は変更できず、ダンジョン・クエストへの出撃もできません。ストーリーは遊べます。イベントには未編成のキャラクターをサブリーダーとして参加させられます。','The expedition party is locked, and dungeon and quest departures are unavailable. Stories remain playable; an unassigned character can enter events as subleader.']]],links:['dungeons','event-guide','story-guide']},
'friends-guide':{title:['冒険者カード ― 自分の仲間を旅の名刺に','Adventurer cards — A calling card for your companion'],intro:['お気に入りのリーダーと装備を、ひとつのカードに。仲間を紹介する楽しみと、共闘の準備がつながります。','Show a favorite leader and loadout on one card. Sharing your companion is also a way to prepare for co-op.'],sections:[
 [['リーダーと装備を整える','Prepare your leader and loadout'],['冒険者カードには仲間のステータス、装備、使用スキル、アビリティカードが表示されます。強さだけでなく、役割が伝わる装備を選んでみましょう。','Adventurer cards show stats, equipment, skills and ability cards. Choose a loadout that communicates your companion’s role as well as their strength.']],
 [['交換コードやQRで登録する','Register through a code or QR image'],['フレンド登録は交換コードや冒険者カード画像のQR読み取りに対応しています。同じフレンドを再登録すると情報が更新されるので、育成後に新しいカードを交換する使い方もできます。','Register friends with exchange codes or QR codes in adventurer-card images. Registering the same friend again updates their information, so exchange a fresh card after training.']],
 [['自分の足りない役割を借りる','Invite the role your team needs'],['共闘に迎える仲間は、火力だけでなく回復・前衛・支援を見て選ぶと組み合わせを考えやすくなります。フレンド本人の同時接続は不要です。','When inviting companions, consider healing, frontline protection and support as well as damage. The friend does not need to be online at the same time.']]],links:['coop-guide','growth','cards-guide']},
'growth-guide':{title:['仲間の育成 ― 好きな一人を長く連れていく','Companion growth — Keep your favorites on the journey'],intro:['レベル、習得スキル、装備、カード。育成はひとつの数字だけではありません。今の仲間に足りないものを探しましょう。','Levels, skills, gear and cards all matter. Find what your companion needs for the next challenge.'],sections:[
 [['訓練所で新しい仲間を追いつかせる','Help new companions catch up'],['主人公以外の仲間はGで訓練できます。訓練のLv上限は主人公Lvの4/5を切り捨てた値と、仲間自身の上限の範囲内です。主人公Lvが上がったら、控えの育成も見直しましょう。','Train companions other than the hero with gold. The training cap is the hero’s level × 4/5, rounded down, within the companion’s own cap. Revisit reserve training after the hero levels up.']],
 [['同じ仲間との出会いも育成になる','Duplicates contribute to growth'],['通常のLv上限は50。同じキャラの獲得で上限が5ずつ上がり、最大100です。現在Lvも★3は3、★4は2、★5は1上がるため、低レアの重複にも役割があります。','The normal level cap is 50. Duplicate characters raise it by 5 up to 100. They also increase current level by 3 for ★3, 2 for ★4 and 1 for ★5, so lower-rarity duplicates still help.']],
 [['レベルで伸びない能力を装備で補う','Use equipment for stats levels do not raise'],['DEF・MDEF・SPD・MOVE・MPはレベルアップだけでは伸びません。耐久や行動順で困ったら防具・アクセサリ・アビリティを確認しましょう。習得Lvの近いスキルを次の育成目標にするのもおすすめです。','DEF, MDEF, SPD, MOVE and MP do not rise simply from leveling. Review gear and abilities if durability or turn order is the problem. A nearby skill unlock can be a useful next goal.']]],links:['growth','characters','cards-guide']}
};
