export function beginnerGuide({D,L,T,esc}){
 const chapters=[
 {title:['まずは物語を進めて、冒険の入口へ','Start with the story and open your adventure'],body:['プロローグでは、移動・攻撃・スキルの基本を覚えながら、ギルドやイベント、訓練所、クエストを順に解放していきます。ストーリーの初回クリアでは召喚石を獲得できる戦いもあります。先へ進めなくなったら、ほかの遊びで仲間を育ててから戻ってきましょう。','The prologue teaches movement, attacks and skills while unlocking the guild, events, training hall and quests. Some story battles award summon stones on their first clear. If progress stalls, grow your companions through other activities before returning.'],image:'9536.jpg',caption:['出撃前に推奨レベルと仲間の操作設定を確認しましょう。','Check the recommended level and companion controls before departure.'],links:[['story-guide',['ストーリー攻略へ','Story guide']]]},
 {title:['召喚石は、休んでいる間も少しずつ','Summon stones grow while you take a break'],body:[`召喚石はプレイ中${D.stoneMinutes.active}分、お休み中${D.stoneMinutes.away}分で1個、自動的に増えていきます。すぐに仲間を増やせなくても、少し時間を置いて戻れば次の召喚につながります。ストーリーの初回報酬も集め、キャンプの「お知らせ」も時々のぞいてみてください。サプライズの配布が届いている時は、そこから召喚石を受け取れます。`,`A summon stone recharges every ${D.stoneMinutes.active} minutes while playing and every ${D.stoneMinutes.away} minutes while away. Even if you cannot summon right now, a break brings the next recruit closer. Collect first-clear story rewards and occasionally check Notices at camp, where surprise gifts can be claimed when available.`],image:'9523.PNG',caption:['焚き火のそばでひと息。お知らせも確認してみましょう。','Take a breather by the fire and check your notices.'],links:[['camp-guide',['キャンプの過ごし方','Life at camp']]]},
 {title:['異世界召喚で、役割の違う仲間を迎えよう','Summon companions with different roles'],body:['召喚石が貯まったら異世界召喚へ。最初はレア度だけで選ばず、敵を受け止めるタンク、回復するヒーラー、敵を倒す攻撃役をそろえると戦いやすくなります。残りの枠には弓や魔法、強化・弱体化を得意とする仲間を。常設・週間ピックアップ・期間限定などの違いと、出現キャラクターを確認して召喚しましょう。','When stones have accumulated, visit Otherworld Summoning. Start by covering tanking, healing and damage rather than chasing rarity alone. Add bows, magic, buffs or debuffs in the remaining slots. Review the character pools and differences between permanent, weekly pickup and limited banners before summoning.'],image:'9545.jpg',caption:['新しい仲間との出会いが、次の編成のきっかけになります。','A new companion can inspire your next party.'],links:[['summons',['異世界召喚を知る','Explore summoning']],['characters',['お気に入りのキャラを探す','Find your favorite companion']]]},
 {title:['ダンジョンでレベルと装備を整える','Build levels and equipment in dungeons'],body:['短いダンジョンは、5人の役割分担を試すのにぴったりです。通常探索で武器や防具を集め、金のトカゲ依頼が出たら経験値とGを狙う育成先として検討しましょう。金のトカゲは常時出現ではなく、Fランクは1階層・スタミナ2。深い依頼ではMPと回復の残り回数も大切になるので、無理なく踏破できる行き先から始めてください。','Short dungeons are a good place to test your five-person team. Gather weapons and armor on regular runs, and consider golden-lizard requests for EXP and gold when they appear. They are not always available; rank F has one floor and costs 2 stamina. Deeper requests demand MP and healing-charge management, so start with reliable clears.'],image:'9525.PNG',caption:['装備集めか育成か、目的を決めて探索先を選びましょう。','Choose a destination to match your goal: equipment or growth.'],links:[['dungeon-guide',['ダンジョンの選び方','Choosing a dungeon']],['growth-guide',['仲間の育て方','Growing your companions']]]},
 {title:['フレンドの力を借りて、イベントの強敵へ','Bring friends into your event adventures'],body:['冒険者カードでフレンドを登録すると、イベントの共闘に参加してくれることがあります。登録は「メニュー → プレイヤーカード／フレンド」から。育ったキャラを共有してもらうと心強い味方になりますが、毎回必ず参加するわけではありません。「仲間と攻略」は自分の参加者1人とNPC・フレンド5人で挑み、戦利品はダイスで選ぶ順番を決めます。','Register friends through adventurer cards and they may join event co-op. Open Menu → Player Card / Friends to register them. A well-trained shared character can be a strong ally, although participation is not guaranteed every run. Co-op uses your participant plus five NPCs or friends, with dice determining loot selection order.'],image:'9550.jpg',caption:['共闘ではNPCやフレンドと一緒に出撃します。画像はNPC参加の例です。','Co-op brings NPCs or friends alongside you; this example shows NPC participants.'],links:[['friends-guide',['フレンド登録の手引き','Friend registration guide']],['coop-guide',['共闘と戦利品のルール','Co-op and loot rules']]]},
 {title:['イベント・クエスト・ダンジョンを巡って強くなる','Grow stronger across events, quests and dungeons'],body:['イベントでは季節のボスと専用カード、クエストでは依頼者の物語やアクセサリ、恒常カードとの出会いが待っています。ダンジョンで装備を整え、依頼で欲しい効果を探し、仲間が育ったらイベントへ。手に入れた装備やカードでパーティを組み直して、止まっていたストーリーに再挑戦しましょう。毎回全部を遊ぶ必要はありません。今日は育成、次は物語と、自分のペースで楽しめます。','Events offer seasonal bosses and dedicated cards; quests bring requester stories, accessories and permanent cards. Equip your party in dungeons, seek useful effects in requests, then challenge events with your stronger companions. Rebuild your team with the rewards and return to a story battle that stopped you. You need not play everything each day: choose growth today and story next time, at your own pace.'],image:'9546.jpg',caption:['季節の冒険も、仲間を強くするための選択肢です。','Seasonal adventures offer another way to strengthen your companions.'],links:[['events',['イベント攻略を読む','Read event strategies']],['quest-guide',['クエストの楽しみ方','Discover quests']]]}
 ];
 return `<p class="article-lead">${esc(T(['仲間を迎え、装備を集め、ときにはフレンドの力も借りて。冒険の楽しみ方を、実際のゲーム画面と一緒に紹介します。','Meet companions, gather equipment, and sometimes call on friends. Discover your adventure through actual game screens.']))}</p>`+chapters.map((c,i)=>`<section class="reading-split beginner-step"><div><span class="eyebrow">STEP ${String(i+1).padStart(2,'0')}</span><h2>${esc(T(c.title))}</h2><p>${esc(T(c.body))}</p><div class="beginner-links">${c.links.map(([route,label])=>`<a href="#${route}">${esc(T(label))} →</a>`).join('')}</div></div><figure class="gameplay-figure"><a href="assets/screenshots/game-${c.image}" target="_blank" rel="noopener"><img src="assets/screenshots/game-${c.image}" alt="${esc(T(c.caption))}" loading="lazy"></a><figcaption>${esc(T(c.caption))}</figcaption></figure></section>`).join('');
}
