import {eventPlans} from './event-plans.js?v=20260921-published';
export function fieldGuides({D,L,T,esc,element,portrait,itemCard,link,section}){
 const p=text=>`<p>${esc(T(text))}</p>`,h=(title,body)=>`<section class="reading-section"><h2>${esc(T(title))}</h2>${body}</section>`;
 const sprite=(src,name)=>src?`<span class="guide-sprite" role="img" aria-label="${esc(L(name))}" style="background-image:url('${esc(src)}')"></span>`:'';
 const photo=(file,caption)=>`<figure class="gameplay-figure"><a href="assets/screenshots/game-${file}" target="_blank" rel="noopener"><img src="assets/screenshots/game-${file}" loading="lazy" alt="${esc(T(caption))}"></a><figcaption>${esc(T(caption))}</figcaption></figure>`;
 const scene=(title,text,file,caption)=>`<section class="reading-split"><div><h2>${esc(T(title))}</h2>${p(text)}</div>${photo(file,caption)}</section>`;
 const rewardCards=items=>`<div class="editorial-rewards">${items.map(itemCard).join('')}</div>`;
 function event(e){
  const g=e.battleGuide,boss=g.enemies.find(u=>u.boss),weak={fire:'water',water:'wind',wind:'fire',light:'dark',dark:'light'}[boss.element],plan=eventPlans[e.id];
  const companions=[...new Set(['gareth','lyra',...plan[0]])].map(id=>D.characters.find(c=>c.id===id));
  const relevant=D.equipment.filter(c=>c.eventId===e.id&&c.abilityCard);
  return `<div class="event-story"><span class="eyebrow">SEASONAL FIELD GUIDE · ${e.month} / ${e.half===1?'01–15':'16–END'} JST</span><h1>${esc(L(e.name))}</h1><p class="article-lead">${esc(L(e.story||e.description))}</p><img class="event-editorial-art" src="${e.art}" alt="${esc(L(e.name))}"></div>`+
   h(['この冒険で待っているもの','What awaits on this expedition'],p(['3フェーズを戦い抜き、最後に巨大ボスへ挑む季節のイベントです。道中でMPを使い切らず、最終戦に回復と主力スキルを残しましょう。ソロは自分の5人で役割を組み立て、共闘では参加する1人の装備と役割を整えて臨みます。','Fight through three phases and face a giant boss at the end. Keep healing and key skills for the finale. Solo lets you build your own five-person formation; in co-op, prepare the role and gear of your participating companion.'])+`<p class="tactic-promise">${esc(L(e.tactics.warning))}</p>`)+
   `<section class="boss-profile">${sprite(boss.sprite,boss.name)}<div><span class="eyebrow">MEET THE BOSS</span><h2>${esc(L(boss.name))}</h2><div class="boss-elements"><span>${esc(T(['属性','Element']))}：${element(boss.element)}</span><strong>${esc(T(['弱点となる攻撃属性','Effective attack element']))}：${element(weak)}</strong></div>${p(['有利属性の攻撃は1.25倍。キャラクターの属性だけでなく、使うスキルの属性を確認して選びましょう。無属性攻撃にはこの有利補正は付きません。','Advantageous attacks deal 1.25× damage. Check the skill’s element rather than relying only on the character’s element. Neutral attacks do not receive this bonus.'])}${['light','dark'].includes(boss.element)?p(['光と闇は互いに有利です。弱点を突ける仲間も相手の属性攻撃で大きなダメージを受けるため、回復役や盾役の支援を用意しましょう。','Light and dark are mutually effective. An ally exploiting the weakness can also take increased elemental damage; bring protection and healing.']):''}${p(['ボスはその場から遠距離攻撃を行います。接近する途中から攻撃を受けるため、全員を同じ場所に固めず、回復が届く間隔を保って進みましょう。','The boss attacks at range without moving. Expect incoming attacks during your approach, spread your party out, and keep healing within reach.'])}</div></section>`+
   h(['何が脅威なのか','What makes this fight dangerous'],`<p class="article-lead">${esc(L(e.tactics.warning))}</p>${p(['ボスの基本技は遠距離からの魔法攻撃です。以下の技に加えて、Cランク以上ではイベント固有の特殊技や能力が加わります。技名だけでなく範囲と効果を確認し、回復役まで同時に巻き込まれない位置を選びましょう。','The boss’s basic skills are ranged magical attacks. At rank C and above, event-specific skills or abilities are added. Check each attack’s area and effect, and position your healer so a single strike cannot catch everyone.'])}<div class="boss-skill-notes">${boss.skills.slice(0,2).map(s=>`<p><strong>${esc(L(s.name))}</strong> — ${esc(L(s.description))}</p>`).join('')}</div><p class="note">${esc(T(['イベント固有の特殊役はCランクから登場します。F〜Dでは、まず通常攻撃とボスの範囲攻撃への対応を練習しましょう。','Event-specific specialists appear from rank C. At F–D, first practice handling ordinary attacks and the boss’s area attacks.']))}</p>`)+
   h(['勝ち筋を作る、3つの段階','Build your approach in three stages'],`<ol class="battle-steps"><li><h3>${esc(T(['道中：危険な特殊役を見つける','Approach: identify the specialists']))}</h3><p>${esc(L(e.tactics.strategy))}</p></li><li><h3>${esc(T(['精鋭戦：攻撃を一体に重ねる','Elites: concentrate your attacks']))}</h3>${p(['全員で別々の敵を削るより、倒し切れる相手を決めて人数を減らします。Hard以上は第2フェーズの敵が増えるので、盾役を先に進ませすぎず、後衛へ届く敵から処理しましょう。','Finishing one target is safer than spreading damage. Hard and above add another enemy to phase two: avoid overextending the tank and deal with enemies threatening the backline.'])}</li><li><h3>${esc(T(['最終戦：護衛とボスを切り分ける','Finale: handle escorts and boss separately']))}</h3>${p(plan[1])}${p(['詠唱予告の範囲に複数人が入ったら、攻撃より退避を優先。ボスへ火力を集める前に、回復役が行動できる位置とMPを確保してください。','If several allies stand in a cast marker, prioritize getting clear. Secure your healer’s position and MP before committing damage to the boss.'])}</li></ol>`)+
   h(['おすすめの役割と仲間の例','Suggested roles and companion examples'],`<p>${esc(L(e.tactics.roles))}</p>${p(['以下は役割をそろえるための候補です。残りの枠には、弱点属性の攻撃スキルを持つ仲間や、手持ちで育っている火力役を加えましょう。解除・回復などの技は必要レベルを満たしているか確認してください。共闘では他の5人を自由に編成できないため、自分の参加者の役割を重視します。','These are examples for covering roles. Fill remaining slots with trained damage dealers or allies whose skills exploit the weakness. Check unlock levels for healing and cleansing. In co-op you cannot freely choose the other five participants, so focus on what your own companion contributes.'])}<div class="recommended-team">${companions.map(c=>`<a href="#character/${c.id}">${portrait(c)}<div><h3>${esc(L(c.name))}</h3><p>${esc(L(c.role))} · ${element(c.element)}</p><small>${esc(T(c.role.ja==='タンク'?['前衛で敵を受け、後衛の攻撃機会を作る。','Hold the frontline and create openings for the backline.']:c.role.ja==='ヒーラー'?['HP回復と習得済みの解除技で継戦を支える。','Sustain the party with healing and unlocked cleansing skills.']:c.role.ja==='デバッファー'?['弱体化で味方の集中攻撃を助ける。','Use debuffs to support focused allied attacks.']:c.role.ja==='バッファー'?['強化で主力の攻撃や生存を支える。','Buff your main attackers and support their survival.']:['育成済みの攻撃技で優先目標を倒す。','Use your unlocked attacks to finish priority targets.']))}</small></div></a>`).join('')}</div>`)+
   h(['登場する敵を知る','Know the enemies you will face'],p(['次はCランク・Normalの敵編成例です。ランクと難易度を変えると道中の顔ぶれも変わります。特殊役にはイベント固有の追加技があり、同じロールでも通常の敵とは対処が異なります。','The following is a rank C / Normal example. Rank and difficulty also change the escort lineup. Specialists gain event-specific abilities, so they may require a different response from ordinary enemies of the same role.'])+`<div class="enemy-phases">${g.waves.map((ids,i)=>`<section><h3>${esc(T(['フェーズ','Phase']))} ${i+1}</h3><div class="enemy-guide-grid">${ids.map(id=>{const u=g.enemies.find(x=>x.id===id);return `<article class="enemy-guide">${sprite(u.sprite,u.name)}<h4>${esc(L(u.name))}</h4><p>${esc(L(u.role))} · ${element(u.element)}${u.specialist?' · '+esc(T(['特殊役','Specialist'])):''}</p>${u.skills.map(s=>`<details><summary>${esc(L(s.name))}</summary><p>${esc(L(s.description))}</p></details>`).join('')}</article>`;}).join('')}</div></section>`).join('')}</div>`)+
   h(['このイベントで狙いたい戦利品','Treasures worth pursuing'],p(['カードは編成との相性を見て選びましょう。説明の対象ロールや効果条件を確認し、今の主力に働くものから集めると、次の難易度へ挑みやすくなります。宝箱や共闘の選択順によって、毎回必ず希望の品を獲得できるわけではありません。','Choose cards that benefit your current party. Check role restrictions and effect conditions, then prioritize upgrades for your main team. Chest rolls and co-op draft order mean your preferred reward is not guaranteed every run.'])+rewardCards(relevant))+scene(['共闘の戦利品は、ダイスの後に選ぶ','Shared loot is chosen after the dice roll'],['「仲間と攻略」はスタミナ2で参加します。参加者がダイスを振り、出目の大きい順に残った品を選びます。装備名だけでなく効果を見比べ、自分の番に欲しい品を選びましょう。','Co-op costs 2 stamina. Participants roll dice and choose remaining loot in descending roll order. Compare effects as well as names before your turn.'],'9558.jpg',['自分の番になると、残った戦利品を選べます。','Choose from the remaining spoils when your turn arrives.']);
 }
 function dungeon(){const golden=D.dungeons.find(q=>q.special&&q.rank==='F'),gear=D.dungeons.filter(q=>q.rank==='F'&&q.reward&&q.difficulty==='Easy').slice(0,7);return scene(['5人で潜り、次の装備を持ち帰る','Explore with five companions and bring back new gear'],['ダンジョンは、仲間5人で階層を進みながら装備と経験値を集める冒険です。短い依頼で編成を試し、装備が整ったら深い依頼へ。火力だけでなく、回復・MP・スキルの使用回数をどう残すかが踏破の鍵になります。','Dungeons send five companions through consecutive floors for equipment and experience. Test your team on short runs before venturing deeper. Healing, MP and skill charges matter as much as damage.'],'9525.PNG',['ギルドの「ダンジョン」から探索先を選びます。','Choose a destination from the guild’s Dungeon tab.'])+
 `<section class="boss-profile">${sprite(D.goldenSprite,{ja:'金のトカゲ',en:'Golden lizard'})}<div><span class="eyebrow">FIRST GROWTH TARGET</span><h2>${esc(T(['初心者は、金のトカゲで育成の足がかりを','Start growing your party with golden-lizard requests']))}</h2>${p(['金のトカゲ依頼は、通常の同じ深さの基礎報酬に比べてEXP3倍・G5倍。Fランクは1階層なので、長い探索に不安がある時の育成先として候補になります。スタミナは2。通常装備のドロップはないため、レベル上げと装備集めで行き先を使い分けましょう。','Golden-lizard requests award 3× EXP and 5× gold compared with the same base depth. Rank F is just one floor, making it a useful growth option before long expeditions. It costs 2 stamina and does not drop regular equipment, so separate leveling runs from gear hunts.'])}${p(['常時出現ではありません。出現抽選は通常20%、日本時間の土日は40%。掲示画面を開き直すだけでは再抽選されません。見つけたら育てたい5人の装備を確認して挑みましょう。','This request is not always available. Its offer roll is 20% normally and 40% on weekends in Japan time. Reopening the board does not reroll it. When it appears, prepare the five companions you want to train.'])}<p>${link('dungeon',golden.id,L(golden.name))} →</p></div></section>`+
 h(['5階層の番人、その先の消耗戦','The fifth-floor guardian and the endurance test beyond'],p(['通常探索では5階層ごとに番人が現れます。6階層目以降は通常敵も増え、Cランク以上ではさらに人数が増加。最初の戦闘で大技を使い切らず、番人を倒すための火力と、後衛を守るための回復を残しておきましょう。','Regular expeditions have a guardian every five floors. Ordinary enemy numbers increase after floor five, with another increase from rank C. Save both burst damage for guardians and healing for your backline.'])+p(['編成の土台は、敵を引き受けるタンク、HPを戻すヒーラー、優先目標を倒す火力役。残りの枠は遠距離攻撃や支援で補います。倒すまで時間がかかるなら火力、途中で崩れるなら回復や防御を見直すと、次に育てたい仲間が見えてきます。','Start with a tank, healer and priority-target attacker, then add ranged damage or support. Slow clears call for more damage; repeated collapses call for better sustain and defense. This helps decide who to train next.']))+
 scene(['7階層以上なら、野営で立て直せる','Longer dungeons include a chance to rest'],['7階層以上の依頼では4〜6階層のどこかが敵のいない野営フロアになり、HP・MP・全スキル回数が全回復します。12階層以上なら9〜11階層にも野営が入ります。場所は出撃時に決まるので、「次は必ず休める」と決めつけず、それまでは消耗を抑えて進みましょう。','Requests with at least seven floors include an enemy-free camp on one of floors 4–6, restoring HP, MP and all skill charges. At twelve or more floors, another camp appears on floors 9–11. Locations are chosen at departure, so conserve resources rather than assuming the next floor is a rest.'],'9532.jpg',['出撃前の説明で野営とバックグラウンド探索の条件を確認できます。','The departure screen explains rest and background-exploration conditions.'])+
 h(['装備を狙うなら、報酬指定の依頼から','Target gear through requests with specified rewards'],p(['剣・弓・槍・杖・投石・重装・軽装の報酬指定依頼は、対応する装備を確実に1個持ち帰れる探索先です。強化値には幅があり、難易度を上げてもその幅は変わりません。まずは踏破できる難易度で、前衛の防具や主力の武器を更新しましょう。','Specified-reward requests guarantee one sword, bow, spear, staff, slingshot, heavy armor or light armor from their category. Enhancement rolls vary, but higher difficulty does not change that range. Start with manageable clears to upgrade frontline armor or your main attacker’s weapon.'])+`<div class="reading-links">${gear.map(q=>`<a href="#dungeon/${q.id}"><strong>${esc(L(q.name))}</strong><span>${esc(L(q.reward))} · ${q.floors} ${esc(T(['階層','floors']))}</span></a>`).join('')}</div>`)+
 h(['リラに教わる、長い探索の休み方','Lyra’s guide to resting during long expeditions'],p(['第一章07のクリア後、リラから省電力モードを学びます。チュートリアルを終えると利用できます。戦闘中のポーズから選び、全員オートで戦う確認に「はい」と答えると、画面を暗くして攻略を続けます。タップで戻れますが、強敵への勝利は保証されません。','After Chapter 1 episode 07, complete Lyra’s tutorial to unlock power-saving mode. Choose it from Pause and confirm that everyone will fight automatically. The screen dims while combat continues; tap to return. Victory against strong enemies is not guaranteed.'])+p(['第一章08のクリア後のチュートリアルで、アプリを閉じたまま進めるダンジョン攻略が解放されます。ダンジョンのポーズから開始し、攻略中の画面になってからアプリを閉じてください。全員オートで進み、次回起動時に状況を確認して再開できます。クエスト入門は第一章02のクリア後です。','After Chapter 1 episode 08, complete the tutorial to unlock dungeon exploration with the app closed. Start it from Pause in a dungeon and wait for the expedition screen before closing the app. Everyone advances automatically; reopen the app to check progress and resume. The quest tutorial follows Chapter 1 episode 02.']))+
 h(['一度の踏破を、次からの放置探索へ','Turn a clear into future background exploration'],p(['クリア編成と所要時間が記録されると、通常よりスタミナを1多く使ってバックグラウンド探索を頼めます。出撃した仲間は帰還まで拘束されますが、サブリーダーを用意すれば、その間のイベント参加を任せられます。まずは安定して勝てる記録を作ることが大切です。','Once the clear party and time are recorded, you can spend one extra stamina on background exploration. Those companions remain busy until they return; prepare a subleader to participate in events meanwhile. Establish a reliable clear first.']));}
 function quests(){const picks=D.quests.slice(0,3);return scene(['依頼書を開くと、小さな物語が始まる','Every request opens a small story'],['クエストは、依頼者との会話を読み、目的に合った戦いをこなし、報酬と後日談を受け取るコンテンツです。経験値や装備だけを集める場所ではなく、仲間やNPCの困りごとをたどる寄り道としても楽しめます。','Quests combine conversations with the requester, a battle built around their objective, rewards and an epilogue. They are not only a source of gear and experience: they are detours into the lives of companions and NPCs.'],'9547.jpg',['掲示板では推奨レベル、報酬、期限を確認してから依頼を読めます。','Review recommended level, rewards and expiry before opening a request.'])+
 h(['用意された物語と、組み合わせで生まれる物語','Authored stories and generated variations'],p(['専用の会話が用意された依頼に加え、通常依頼は依頼の目的、登場人物、舞台などの組み合わせから生まれます。同じ掲示板でも、次に出会う事情や会話は変わります。「無限の手書きシナリオ」という意味ではなく、組み合わせで繰り返し新しい依頼を楽しめる仕組みです。','Alongside requests with dedicated dialogue, ordinary requests combine objectives, characters and settings into new variations. The circumstances and conversations change as the board refreshes. This is a system for repeatable generated variety, rather than an infinite collection of individually authored scripts.'])+p(['まずは「依頼を読む」から導入を確認しましょう。護衛が目的なら同行者の生存、討伐なら危険な敵の処理など、目的によって立ち回りが変わります。読む時間も冒険の一部として、気になる依頼者から選ぶのもおすすめです。','Start with Read Request to learn the setup. Escort objectives require protecting the guest; combat requests reward prioritizing dangerous enemies. Choose a requester who interests you and make the story part of the adventure.']))+
 h(['確率で届く恒常依頼で、専用カードを集めよう','Collect dedicated cards from permanent requests'],p(['45種類の恒常カード依頼は、独立した2枠でそれぞれ10%の登場抽選があります。一度出現すればクリアまで残るため、今は難しくても仲間を育ててから再挑戦できます。クリアで手に入る専用カードは、ロールや武器、パペットなどの条件が合う編成で活かしましょう。期間限定イベントのカードとは別の収集先です。','The 45 permanent card requests use two independent slots, each with a 10% appearance roll. Once posted, a request remains until cleared, so you can train and retry. Match its dedicated card to role, weapon or puppet conditions. These are separate from time-limited event cards.'])+rewardCards(picks.map(q=>D.equipment.find(c=>c.id===q.cardId)))+`<div class="reading-links">${picks.map(q=>`<a href="#quest/${q.id}"><strong>${esc(L(q.name))}</strong><span>${esc(L(q.description))}</span><small>${esc(T(['導入と報酬を読む','Read the introduction and reward']))} →</small></a>`).join('')}</div>`)+
 scene(['短い依頼で装備を整え、レア依頼を見逃さない','Build your gear through short requests and watch for rare ones'],['通常依頼はスタミナ1で、生成時に50%の確率でアクセサリ報酬が設定されます。欲しい効果が表示されている依頼を選ぶと、育成の目的を持ちやすくなります。レア依頼は期限や推奨レベルも確認。「危険」の表示がある時は報酬につられて急がず、編成と勝利条件を読み直しましょう。','Ordinary requests cost 1 stamina and have a 50% chance to receive an accessory reward when generated. Choose a displayed effect that helps your party. Check expiry and recommended levels on rare requests. A danger warning is a reason to review your formation and victory conditions before pursuing the reward.'],'9536.jpg',['出撃前に操作方法と参加メンバーを確認。画像はストーリー出撃画面の例です。','Check controls and participants before departure. This image shows a story departure screen.']);}
 return {event,dungeon,quests};
}
