import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=fileURLToPath(new URL('../',import.meta.url)),source=path.resolve(process.argv[2]||process.env.GAME_SOURCE||'../game-source'),dist=path.join(source,'dist');
const mod=async name=>import(pathToFileURL(path.join(dist,name+'.js')).href);
const {CHARACTERS,SKILLS,EQUIPMENT,MISSIONS,ENEMIES}=await mod('data');
const {setLanguage,t}=await mod('i18n');const {skillEffect}=await mod('skill-text');const {skillUnlockLevel}=await mod('skill-progression');
const {DUNGEON_QUESTS,GOLDEN_LIZARD_QUESTS,dungeonRewards,dungeonStaminaCost}=await mod('dungeon');const {DROP_QUESTS}=await mod('dungeon-drop-quests');
const {RANKS,RANK_POINTS,eventStage,eventMission,EVENT_CHEST_CHANCE,normalPool}=await mod('live-content');const {SEASONS}=await mod('seasonal-data');const {CAMP_TOOLS}=await mod('camp-tools');
const {PERMANENT_QUESTS,permanentQuestStory}=await mod('permanent-quests');const {SPECIAL_QUESTS}=await mod('quests');const {CHARACTER_ART,loadPortraitArt}=await mod('character-art-data');
const {isSummonable}=await mod('character-availability');const {STAMINA_RECOVERY_MINUTES}=await mod('stamina-config');const {STONE_CHARGE_MS,AWAY_STONE_CHARGE_MS}=await mod('stone-charge');
const overrides=JSON.parse(await fs.readFile(path.join(root,'data/translation-overrides.json'),'utf8'));
const bi=value=>{if(value==null)return null;const out={};for(const lang of ['ja','en']){setLanguage(lang);out[lang]=lang==='en'&&overrides[value]?overrides[value]:t(String(value));}return out;};
const pick=(o,keys)=>Object.fromEntries(keys.filter(k=>o[k]!=null).map(k=>[k,o[k]]));
const stats=o=>pick(o,['hp','mp','atk','mag','def','mdef','spd','move','range']);
const assets=new Set();const asset=p=>{if(!p||!p.startsWith('/assets/'))return null;assets.add(p);return p.slice(1);};
function skill(id){const s=SKILLS[id];setLanguage('ja');const description=skillEffect(s);return {id,...pick(s,['mp','range','area','areaShape','cast','jumpCT','power','element','type','status','statusChance','turns']),uses:Number.isFinite(s.uses)?s.uses:'∞',name:bi(s.name),description:bi(description)};}
const characters=CHARACTERS.map(c=>({id:c.id,name:bi(c.name),title:bi(c.title),greeting:bi(c.greeting),description:bi(c.bio||c.combatStyle||''),role:bi(c.role),race:bi(c.raceName),gender:c.gender,element:c.element,rarity:c.rarity,stats:stats(c),portrait:CHARACTER_ART[c.sprite]?.portrait??null,art:c.id==='rukiwa'?asset('/assets/characters/rukiwa-puppet-motions-v1.png'):['milena','nonoa'].includes(c.id)?asset('/assets/characters/milena-nonoa-motions-v1.png'):null,source:'data.js',acquisition:!isSummonable(c)?'story':c.sundayExclusive?'sunday':c.festivalExclusive|| (c.limited?'limited':'normal'),seasonId:c.seasonId,skills:c.skills.map(id=>({id,level:skillUnlockLevel(c,id)})).filter(s=>Number.isFinite(s.level)),abilities:(c.abilityCatalog||[]).map(a=>({id:a.id,name:bi(a.name),description:bi(a.description),level:a.level}))}));
const equipment=Object.entries(EQUIPMENT).map(([id,e])=>({id,name:bi(e.name),description:bi(e.desc||e.description||''),...pick(e,['slot','tier','level','stats','weaponType','armorType','roles','eventId','permanentQuest','questReward','abilityCard','partyEffect','wearerEffect']),art:asset(e.art),source:e.permanentQuest?'permanent-cards-data.js':e.abilityCard?'ability-cards-data.js':id.startsWith('quest-')?'quest-accessories.js':id.startsWith('loot_')?'seasonal-data.js':'data.js'}));
const missions=MISSIONS.map(m=>({id:m.id,name:bi(m.name),description:bi(m.text),chapter:m.chapter,arc:m.storyArc===2?2:m.chapter?.includes('PROLOGUE')?0:1,level:m.level,gold:m.reward,xp:m.xp,crystals:m.crystals,requires:m.requires,phases:m.waves?.length||1,goal:bi(m.goal),terrain:bi(m.mapMetadata?.terrainLabel),art:asset(m.mapMetadata?.artSource),enemies:[...new Set((m.waves||[m]).flatMap(w=>(w.enemies||[]).map(e=>e[0])))].map(id=>{const e=m.enemyDefinitions?.[id]||ENEMIES[id];return{id,name:bi(e?.name||id),role:bi(e?.role),skills:e?.skills||[]};}),source:m.storyArc===2?'chapter-two.js':'data.js'}));
const quests=PERMANENT_QUESTS.map(q=>{const stories={};for(const lang of ['ja','en']){setLanguage(lang);stories[lang]=[false,true].map(after=>{const s=permanentQuestStory(q,after);return s.lines.map(l=>({speaker:l.speaker?t(s.actors[l.speaker].name):'',text:l.text}));});}return{id:q.id,name:bi(q.title),description:bi(q.objective),level:q.level,phases:q.floors,stamina:q.stamina,cardId:q.cardId,xp:q.xp,gold:q.gold,stories,source:'permanent-quests.js'};});
const dungeons=[...DUNGEON_QUESTS,...GOLDEN_LIZARD_QUESTS,...DROP_QUESTS].map(q=>({id:q.id,name:bi(q.title),description:bi(q.description),rank:RANKS[q.rank],floors:q.floors,difficulty:q.difficultyLabel||null,stamina:dungeonStaminaCost(q),rewards:dungeonRewards(q),reward:bi(q.rewardRangeName),special:!!q.goldenLizard,source:q.guaranteedReward?'dungeon-drop-quests.js':'dungeon.js'}));
const eventStrategies=JSON.parse(await fs.readFile(path.join(root,'data/event-strategies.json'),'utf8'));
const {MOTION_ART,MOTION_LOADERS}=await mod('character-motion-data');
const spriteAssets={};
async function spriteAsset(id){if(spriteAssets[id])return spriteAssets[id];const info=MOTION_ART[id];if(!info)return null;const m=await MOTION_LOADERS[info.atlas]();const match=m.default[id]?.match(/^data:image\/(\w+);base64,(.+)$/s);if(!match)return null;const dest='assets/guide-sprites/'+id+'.'+match[1];await fs.mkdir(path.join(root,'assets/guide-sprites'),{recursive:true});await fs.writeFile(path.join(root,dest),Buffer.from(match[2],'base64'));return spriteAssets[id]=dest;}
const battleGuides={};
for(const e of SEASONS){const mission=eventMission(e,3,1,[]);const enemies=[];for(const [id,u] of Object.entries(mission.enemyDefinitions)){enemies.push({id,name:bi(u.name),role:bi(u.role),element:u.element,boss:!!u.boss,specialist:!!u.eventSpecialist,sprite:await spriteAsset(u.sprite),skills:u.skills.map(skill),stats:stats(u)});}battleGuides[e.id]={enemies,waves:mission.waves.map(w=>w.enemies.map(x=>x[0]))};}
const goldenSprite=await spriteAsset('boss_golden_lizard');
const events=SEASONS.map(e=>({battleGuide:battleGuides[e.id],id:e.id,tactics:eventStrategies[e.id],name:bi(e.title),boss:bi(e.boss),description:bi(e.description),story:{ja:(setLanguage('ja'),t('event.story.'+e.id)),en:(setLanguage('en'),t('event.story.'+e.id))},month:e.month,half:e.half,characterId:e.characterId,art:asset('/assets/event-key-art/'+e.id+'-v1.png'),source:'seasonal-data.js',stages:RANKS.flatMap((rank,r)=>Array.from({length:5},(_,d)=>({rank,...eventStage(e,r,d)})))}));
const camp=Object.values(CAMP_TOOLS).map(c=>({id:c.id,name:bi(c.name),description:bi(c.desc),tier:c.tier,chance:c.chance,source:'camp-tools.js'}));
const specialQuests=SPECIAL_QUESTS.map(q=>({id:q.id,name:bi(q.title),xp:(q.id==='metal'?1.5:1.2)*.5,gold:q.gold*.5,protect:!!q.protect,source:'quests.js'}));
const commit=execFileSync('git',['-C',source,'rev-parse','HEAD'],{encoding:'utf8'}).trim();
const data={goldenSprite,hero:asset('/assets/dungeon-exploration-lantern-v1.png'),meta:{commit,updated:execFileSync('git',['-C',source,'show','-s','--format=%cI','HEAD'],{encoding:'utf8'}).trim(),languages:['ja','en']},characters,skills:Object.keys(SKILLS).map(skill),equipment,missions,quests,dungeons,events,camp,specialQuests,ranks:RANKS.map((name,i)=>({name,points:RANK_POINTS[i]})),normalPool:normalPool().map(c=>c.id),chestChance:EVENT_CHEST_CHANCE,staminaMinutes:STAMINA_RECOVERY_MINUTES,stoneMinutes:{active:STONE_CHARGE_MS/60000,away:AWAY_STONE_CHARGE_MS/60000}};
// Preserve original art bytes. No whole game bundle or save data is published.
for(const p of assets){const dest=path.join(root,p);await fs.mkdir(path.dirname(dest),{recursive:true});await fs.copyFile(path.join(dist,p),dest);}
const portrait=(await loadPortraitArt()).default;const match=portrait.match(/^data:image\/(\w+);base64,(.+)$/s);if(!match)throw Error('Unknown portrait atlas');data.portraitAtlas='assets/portraits.'+match[1];await fs.writeFile(path.join(root,data.portraitAtlas),Buffer.from(match[2],'base64'));
await fs.mkdir(path.join(root,'data'),{recursive:true});await fs.writeFile(path.join(root,'data/game.json'),JSON.stringify(data,(key,value)=>['source','repository','commit'].includes(key)?undefined:value));
console.log(`Source ${commit.slice(0,7)}: ${characters.length} characters, ${equipment.length} equipment/cards, ${quests.length} card quests, ${events.length} events, ${missions.length} battles; ${assets.size} original assets.`);
